### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by JanPalasek** [jakub-tucek/clusterize#10]
Configuration yml:
```yml
iterations:
  ...
general:
  storagePath: 'out-python'
  sourcesPath: 'src'
  maxResubmits: 3
taskType:
  type: PYTHON # type of runner
  command: |-
    sh ...
resources:
  profile: 'CUSTOM'
  resourceType: 'GPU' # 'GPU'
  details: # Optional
    chunks: 1 # Optional
    walltime: "23:30:00" # Optional
    mem: "80gb" # Optional
    ncpus: 1 # Optional
    scratchLocal: "3gb" # Optional
    ngpus: 1 # Optional
    cpuFlag: "avx512dq" # Optional
  modules: # Optional
    - tensorflow-2.0.0-gpu-python3
    - cudnn-7.6.4-cuda10.0
```

When using the clusterize with relative paths on praha1 metacentrum frontend node (/storage/praha1/home/${USER}), the script generates the following in the inner_script.sh:

```sh
echo "start: "`date --utc +%FT%T` > /auto/vestec1-elixir/home/${USER}/.../job.info
```

This path /auto/vestec1-elixir/... is valid on the frontend node (and according to https://wiki.metacentrum.cz/wiki/NFS4_Servery), but it doesn't work on some GPU nodes because directory /auto does not exist there.

The workaround is to specify absolute paths to the clusterize configuration file instead of the relative paths, for example:
```
storagePath: '/storage/praha1/home/${USER}/.../out-python'
storagePath: '/storage/praha1/home/${USER}/.../src'
```
